import assert from 'node:assert/strict';
import test from 'node:test';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
const require = createRequire(import.meta.url);
process.env.TS_NODE_PROJECT = fileURLToPath(new URL('../apps/api/tsconfig.json', import.meta.url)); require('ts-node/register');
const { LearningSessionActionService } = require('../apps/api/src/study/learning-session-action.service.ts');
const { ActionDomainError } = require('../apps/api/src/study/recommendation-action.service.ts');

class Actions { constructor(status = 'CREATED', userId = 'u-1') { this.status = status; this.userId = userId; } async getAction(userId, id) { if (id === 'missing') throw new ActionDomainError('ACTION_NOT_FOUND'); if (userId !== this.userId) throw new ActionDomainError('ACTION_FORBIDDEN'); return { id, userId, status: this.status, targetType: 'QUESTION', targetId: 'q-1' }; } }
class Sessions { constructor() { this.rows = new Map(); this.created = 0; } async findByActionId(id) { return this.rows.get(id) ?? null; } async createFromAction(s) { this.created++; const old = this.rows.get(s.actionId); if (old) return old; this.rows.set(s.actionId, s); return s; } async save(s) { this.rows.set(s.actionId, s); } }
const run = async (status = 'CREATED') => { const sessions = new Sessions(); const service = new LearningSessionActionService(new Actions(status), sessions); return { service, sessions }; };

test('created action creates attributed session', async () => { const { service } = await run(); const s = await service.createLearningSessionFromAction({ userId: 'u-1', actionId: 'a-1', resourceId: 'r-1' }); assert.equal(s.actionId, 'a-1'); });
test('started action creates attributed session', async () => { const { service } = await run('STARTED'); const s = await service.createLearningSessionFromAction({ userId: 'u-1', actionId: 'a-1', resourceId: 'r-1' }); assert.equal(s.actionId, 'a-1'); });
for (const status of ['COMPLETED', 'CANCELLED', 'EXPIRED']) test(`rejects ${status} action`, async () => { const { service } = await run(status); await assert.rejects(() => service.createLearningSessionFromAction({ userId: 'u-1', actionId: 'a-1', resourceId: 'r-1' }), (e) => e.code === 'ACTION_INVALID_TRANSITION'); });
test('missing action returns not found', async () => { const { service } = await run(); await assert.rejects(() => service.createLearningSessionFromAction({ userId: 'u-1', actionId: 'missing', resourceId: 'r-1' }), (e) => e.code === 'ACTION_NOT_FOUND'); });
test('foreign action is forbidden', async () => { const { service } = await run(); await assert.rejects(() => service.createLearningSessionFromAction({ userId: 'u-2', actionId: 'a-1', resourceId: 'r-1' }), (e) => e.code === 'ACTION_FORBIDDEN'); });
test('same action is idempotent', async () => { const { service, sessions } = await run(); const a = await service.createLearningSessionFromAction({ userId: 'u-1', actionId: 'a-1', resourceId: 'r-1' }); const b = await service.createLearningSessionFromAction({ userId: 'u-1', actionId: 'a-1', resourceId: 'r-2' }); assert.equal(a.id, b.id); assert.equal(sessions.created, 1); });
test('different actions create different sessions', async () => { const { service } = await run(); const a = await service.createLearningSessionFromAction({ userId: 'u-1', actionId: 'a-1', resourceId: 'r-1' }); const b = await service.createLearningSessionFromAction({ userId: 'u-1', actionId: 'a-2', resourceId: 'r-1' }); assert.notEqual(a.id, b.id); });
test('duplicate action cannot create a second session', async () => { const { service, sessions } = await run(); await service.createLearningSessionFromAction({ userId: 'u-1', actionId: 'a-1', resourceId: 'r-1' }); await service.createLearningSessionFromAction({ userId: 'u-1', actionId: 'a-1', resourceId: 'r-1' }); assert.equal(sessions.rows.size, 1); });
test('session keeps action identity distinct from resource and session ids', async () => { const { service } = await run(); const s = await service.createLearningSessionFromAction({ userId: 'u-1', actionId: 'a-1', resourceId: 'r-1' }); assert.notEqual(s.actionId, s.id); assert.notEqual(s.actionId, s.resourceId); });
test('question target is carried as question id, not action id', async () => { const { service } = await run(); const s = await service.createLearningSessionFromAction({ userId: 'u-1', actionId: 'a-1', resourceId: 'r-1' }); assert.deepEqual(s.questionIds, ['q-1']); assert.notEqual(s.questionIds[0], s.actionId); });
test('persistence failure does not return a partial session', async () => { const actions = new Actions(); const sessions = new Sessions(); sessions.createFromAction = async () => { throw new Error('db failed'); }; const service = new LearningSessionActionService(actions, sessions); await assert.rejects(() => service.createLearningSessionFromAction({ userId: 'u-1', actionId: 'a-1', resourceId: 'r-1' })); assert.equal(sessions.rows.size, 0); });
test('direct sessions remain actionless', () => { const direct = { id: 's-1', resourceId: 'r-1' }; assert.equal(direct.actionId, undefined); });
test('metadata is accepted without changing attribution identity', async () => { const { service } = await run(); const s = await service.createLearningSessionFromAction({ userId: 'u-1', actionId: 'a-1', resourceId: 'r-1', metadata: { source: 'recommendation' } }); assert.equal(s.actionId, 'a-1'); });
