import { Check, Download, Save } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import type { QuestionImportCandidate } from '../../../api';

type Draft = Pick<QuestionImportCandidate, 'stem' | 'duplicateAction'>;
function downloadErrors(candidates: QuestionImportCandidate[]) { const rows = [['行/页码', '字段', '代码', '原因', '建议']]; candidates.flatMap((candidate) => candidate.warnings.map((warning) => [String(candidate.sourceRowNumber ?? candidate.sourcePageNumber ?? ''), warning.field ?? '', warning.code, warning.message, warning.suggestion])).forEach((row) => rows.push(row)); const csv = `\uFEFF${rows.map((row) => row.map((cell) => `"${cell.replaceAll('"', '""')}"`).join(',')).join('\r\n')}`; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); link.download = 'question-import-errors.csv'; link.click(); URL.revokeObjectURL(link.href); }

export function CandidateReview({ candidates, onBulkApprove, onUpdate, onConfirm }: { candidates: QuestionImportCandidate[]; onBulkApprove: (items: QuestionImportCandidate[]) => Promise<void>; onUpdate: (candidate: QuestionImportCandidate, patch: Record<string, unknown>) => Promise<void>; onConfirm: (items: QuestionImportCandidate[]) => Promise<void> }) {
  const [abnormalOnly, setAbnormalOnly] = useState(false); const [confirmVersion, setConfirmVersion] = useState(false); const [selectedIds, setSelectedIds] = useState<string[]>([]); const [drafts, setDrafts] = useState<Record<string, Draft>>({}); const [savingId, setSavingId] = useState<string>(); const [saveError, setSaveError] = useState('');
  useEffect(() => { setSelectedIds((ids) => ids.filter((id) => candidates.some((candidate) => candidate.id === id))); setDrafts(Object.fromEntries(candidates.map((candidate) => [candidate.id, { stem: candidate.stem, duplicateAction: candidate.duplicateAction }]))); }, [candidates]);
  const shown = useMemo(() => abnormalOnly ? candidates.filter((candidate) => candidate.warnings.length || candidate.status === 'duplicate_suspected' || candidate.status === 'needs_edit') : candidates, [abnormalOnly, candidates]); const selected = shown.filter((candidate) => selectedIds.includes(candidate.id)); const warningFree = selected.filter((candidate) => candidate.warnings.length === 0 && ['pending_review', 'duplicate_suspected'].includes(candidate.status)); const approved = selected.filter((candidate) => candidate.status === 'approved');
  function toggle(id: string) { setSelectedIds((ids) => ids.includes(id) ? ids.filter((value) => value !== id) : [...ids, id]); }
  async function save(candidate: QuestionImportCandidate) { const draft = drafts[candidate.id]; if (!draft) return; setSavingId(candidate.id); setSaveError(''); try { await onUpdate(candidate, draft); } catch (reason) { setSaveError(reason instanceof Error ? reason.message : '保存失败；请刷新后重试。'); } finally { setSavingId(undefined); } }
  async function confirm() { if (approved.some((candidate) => (drafts[candidate.id] ?? candidate).duplicateAction === 'new_version') && !confirmVersion) { setConfirmVersion(true); return; } await onConfirm(approved); setConfirmVersion(false); }
  return <section className="panel question-import-review"><div className="panel-heading"><div><p className="eyebrow">候选题审核</p><h3>当前页 {candidates.length} 项 · 已选 {selected.length} 项</h3></div><div className="panel-actions"><label><input type="checkbox" checked={abnormalOnly} onChange={(event) => setAbnormalOnly(event.target.checked)} /> 仅显示异常</label><button type="button" className="secondary-action" onClick={() => downloadErrors(candidates)}><Download size={16} /> 下载错误 CSV</button><button type="button" disabled={!warningFree.length} onClick={() => onBulkApprove(warningFree)}><Check size={16} /> 批量通过所选无警告项</button></div></div>{saveError ? <p className="task-status">{saveError}</p> : null}<div className="question-import-candidates">{shown.map((candidate) => { const draft = drafts[candidate.id] ?? { stem: candidate.stem, duplicateAction: candidate.duplicateAction }; return <article key={candidate.id}><header><label><input type="checkbox" checked={selectedIds.includes(candidate.id)} onChange={() => toggle(candidate.id)} /> 选择 #{candidate.sourceRowNumber ?? candidate.sourcePageNumber ?? candidate.id}</label><span>{candidate.status}</span></header><textarea aria-label="题干" value={draft.stem} onChange={(event) => setDrafts((current) => ({ ...current, [candidate.id]: { ...draft, stem: event.target.value } }))} /><p>{candidate.warnings.length ? candidate.warnings.map((warning) => `${warning.code}: ${warning.message}`).join('；') : '无格式警告'}</p>{candidate.exactDuplicates?.length ? <p>完全重复：{candidate.exactDuplicates.map((item) => item.stem).join('；')}</p> : null}{candidate.similarDuplicates?.length ? <p>相似题：{candidate.similarDuplicates.map((item) => item.stem).join('；')}</p> : null}<label>重复处理策略<select value={draft.duplicateAction} onChange={(event) => setDrafts((current) => ({ ...current, [candidate.id]: { ...draft, duplicateAction: event.target.value as Draft['duplicateAction'] } }))}><option value="skip">skip — 跳过，不创建题目</option><option value="create">create — 新建独立题目</option><option value="new_version">new_version — 创建新版本</option></select></label><button type="button" className="secondary-action" disabled={savingId === candidate.id} onClick={() => void save(candidate)}><Save size={16} /> {savingId === candidate.id ? '保存中…' : '保存编辑'}</button></article>; })}</div><footer className="question-import-confirm"><span>确认摘要：将提交所选且已通过的 {approved.length} 项；skip 不创建题目。</span>{confirmVersion ? <p>包含“新版本”操作。请再次确认以创建不可变新版本。</p> : null}<button type="button" disabled={!approved.length} onClick={() => void confirm()}>确认导入</button></footer></section>;
}
