import { Check, Download, Save } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { QuestionImportCandidate } from '../../../api';

function downloadErrors(candidates: QuestionImportCandidate[]) { const rows = [['行/页码', '字段', '代码', '原因', '建议']]; candidates.flatMap((candidate) => candidate.warnings.map((warning) => [String(candidate.sourceRowNumber ?? candidate.sourcePageNumber ?? ''), warning.field ?? '', warning.code, warning.message, warning.suggestion])).forEach((row) => rows.push(row)); const csv = `\uFEFF${rows.map((row) => row.map((cell) => `"${cell.replaceAll('"', '""')}"`).join(',')).join('\r\n')}`; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); link.download = 'question-import-errors.csv'; link.click(); URL.revokeObjectURL(link.href); }

export function CandidateReview({ candidates, onBulkApprove, onUpdate, onConfirm }: { candidates: QuestionImportCandidate[]; onBulkApprove: (items: QuestionImportCandidate[]) => Promise<void>; onUpdate: (candidate: QuestionImportCandidate, patch: Record<string, unknown>) => Promise<void>; onConfirm: (items: QuestionImportCandidate[]) => Promise<void> }) {
  const bulkApprove = onBulkApprove; const [abnormalOnly, setAbnormalOnly] = useState(false); const [confirmVersion, setConfirmVersion] = useState(false); const shown = useMemo(() => abnormalOnly ? candidates.filter((candidate) => candidate.warnings.length || candidate.status === 'duplicate_suspected' || candidate.status === 'needs_edit') : candidates, [abnormalOnly, candidates]); const warningFree = shown.filter((candidate) => candidate.warnings.length === 0 && ['pending_review', 'duplicate_suspected'].includes(candidate.status)); const approved = candidates.filter((candidate) => candidate.status === 'approved');
  async function confirm() { if (approved.some((candidate) => candidate.duplicateAction === 'new_version') && !confirmVersion) { setConfirmVersion(true); return; } await onConfirm(approved); setConfirmVersion(false); }
  return <section className="panel question-import-review"><div className="panel-heading"><div><p className="eyebrow">候选题审核</p><h3>待审核 {candidates.length} 项 · 已通过 {approved.length} 项</h3></div><div className="panel-actions"><label><input type="checkbox" checked={abnormalOnly} onChange={(event) => setAbnormalOnly(event.target.checked)} /> 仅显示异常</label><button type="button" className="secondary-action" onClick={() => downloadErrors(candidates)}><Download size={16} /> 下载错误 CSV</button><button type="button" disabled={!warningFree.length} onClick={() => bulkApprove(warningFree)}><Check size={16} /> 批量通过无警告项</button></div></div><div className="question-import-candidates">{shown.map((candidate) => <article key={candidate.id}><header><strong>#{candidate.sourceRowNumber ?? candidate.sourcePageNumber ?? candidate.id}</strong><span>{candidate.status}</span></header><textarea aria-label="题干" value={candidate.stem} onChange={(event) => onUpdate(candidate, { stem: event.target.value })} /><p>{candidate.warnings.length ? candidate.warnings.map((warning) => `${warning.code}: ${warning.message}`).join('；') : '无格式警告'}</p>{candidate.exactDuplicates?.length ? <p>完全重复：{candidate.exactDuplicates.map((item) => item.stem).join('；')}</p> : null}{candidate.similarDuplicates?.length ? <p>相似题：{candidate.similarDuplicates.map((item) => item.stem).join('；')}</p> : null}<label>重复处理策略<select value={candidate.duplicateAction} onChange={(event) => onUpdate(candidate, { duplicateAction: event.target.value })}><option value="skip">skip — 跳过，不创建题目</option><option value="create">create — 新建独立题目</option><option value="new_version">new_version — 创建新版本</option></select></label><button type="button" className="secondary-action" onClick={() => onUpdate(candidate, { stem: candidate.stem })}><Save size={16} /> 保存编辑</button></article>)}</div><footer className="question-import-confirm"><span>确认摘要：将提交 {approved.length} 项；skip 不创建题目。</span>{confirmVersion ? <p>包含“新版本”操作。请再次确认以创建不可变新版本。</p> : null}<button type="button" disabled={!approved.length} onClick={confirm}>确认导入</button></footer></section>;
}
