import { Download, Upload } from 'lucide-react';
import { useState } from 'react';
import { downloadQuestionImportTemplate, type CreateImportMetadata } from '../../../api';

export function NewImportPanel({ defaults, onSubmit }: { defaults: Pick<CreateImportMetadata, 'source' | 'year' | 'defaultSubject' | 'defaultChapter'>; onSubmit: (file: File, metadata: CreateImportMetadata) => Promise<void> }) {
  const [file, setFile] = useState<File>(); const [metadata, setMetadata] = useState<CreateImportMetadata>({ ...defaults, rightsConfirmed: false }); const [busy, setBusy] = useState(false);
  const update = (key: keyof CreateImportMetadata, value: string | number | boolean) => setMetadata((current) => ({ ...current, [key]: value }));
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!file || !metadata.source?.trim() || !metadata.rightsConfirmed) return; setBusy(true); try { await onSubmit(file, metadata); setFile(undefined); } finally { setBusy(false); } }
  return <section className="panel question-import-new"><div className="panel-heading"><div><p className="eyebrow">题库文档导入</p><h3>新建导入批次</h3></div><button type="button" className="secondary-action" onClick={() => void downloadQuestionImportTemplate('xlsx')}><Download size={16} /> 下载模板</button></div>
    <form className="question-import-form" onSubmit={submit}><label>导入文件<input type="file" accept=".xlsx,.csv,.pdf" required onChange={(event) => setFile(event.target.files?.[0])} /></label><label>来源<input required name="source" value={metadata.source ?? ''} onChange={(event) => update('source', event.target.value)} /></label><label>年份<input type="number" value={metadata.year ?? ''} onChange={(event) => update('year', event.target.value ? Number(event.target.value) : '')} /></label><label>学科<input value={metadata.defaultSubject ?? ''} onChange={(event) => update('defaultSubject', event.target.value)} /></label><label>章节<input value={metadata.defaultChapter ?? ''} onChange={(event) => update('defaultChapter', event.target.value)} /></label>
      {file?.name.toLowerCase().endsWith('.pdf') ? <p className="question-import-notice">PDF 将发送至第三方解析服务处理；请仅上传已获授权的材料。</p> : null}<details><summary>高级选项：页码范围与解析提供商</summary><label>页码范围<input value={metadata.pageRange ?? ''} onChange={(event) => update('pageRange', event.target.value)} placeholder="例如 1-20" /></label><p className="question-import-notice">后端尚未支持手动选择解析提供商；系统会按文件类型自动选择。</p></details><label className="question-import-rights"><input type="checkbox" checked={metadata.rightsConfirmed} onChange={(event) => update('rightsConfirmed', event.target.checked)} /> 我确认拥有该文档的导入与处理权限</label><button type="submit" disabled={!file || !metadata.source?.trim() || !metadata.rightsConfirmed || busy}><Upload size={16} /> {busy ? '正在提交…' : '创建导入'}</button></form></section>;
}
