import { useEffect, useRef, useState } from 'react';
import { getImportPagePreview, getQuestionImportAsset, uploadCandidateAsset, deleteCandidateAsset } from '../../../api';
import type { SourceRegion } from './SourcePagePreview';

const toBlob = (canvas: HTMLCanvasElement) => new Promise<Blob>((resolve, reject) => canvas.toBlob((blob) => blob ? resolve(blob) : reject(new Error('无法导出裁剪图片')), 'image/png'));
export function QuestionAssetEditor({ batchId, candidateId, pageNumber, assetIds, onChange }: { batchId: string; candidateId: string; pageNumber?: number | null; assetIds: string[]; onChange: (assetIds: string[]) => void }) {
  const [assetUrls, setAssetUrls] = useState<Record<string, string>>({}); const [pageUrl, setPageUrl] = useState<string>(); const [start, setStart] = useState<{ x: number; y: number }>(); const [end, setEnd] = useState<{ x: number; y: number }>(); const canvas = useRef<HTMLCanvasElement>(null);
  useEffect(() => { let active = true; const urls: string[] = []; Promise.all(assetIds.map(async (id) => { const response = await getQuestionImportAsset(id); if (!response.ok) return [id, ''] as const; const url = URL.createObjectURL(await response.blob()); if (!active) { URL.revokeObjectURL(url); return [id, ''] as const; } urls.push(url); return [id, url] as const; })).then((entries) => { if (active) setAssetUrls(Object.fromEntries(entries)); }); return () => { active = false; urls.forEach((url) => URL.revokeObjectURL(url)); }; }, [assetIds]);
  useEffect(() => { if (!pageNumber) return undefined; let active = true; let url = ''; getImportPagePreview(batchId, pageNumber).then(async (response) => { if (!response.ok) return; url = URL.createObjectURL(await response.blob()); if (!active) { URL.revokeObjectURL(url); return; } setPageUrl(url); }).catch(() => undefined); return () => { active = false; if (url) URL.revokeObjectURL(url); }; }, [batchId, pageNumber]);
  useEffect(() => { const element = canvas.current; if (!element || !pageUrl) return; const image = new Image(); image.onload = () => { element.width = image.naturalWidth; element.height = image.naturalHeight; element.getContext('2d')?.drawImage(image, 0, 0); }; image.src = pageUrl; }, [pageUrl]);
  async function remove(assetId: string) { await deleteCandidateAsset(candidateId, assetId); onChange(assetIds.filter((id) => id !== assetId)); }
  function point(event: React.MouseEvent<HTMLCanvasElement>) { const rect = event.currentTarget.getBoundingClientRect(); return { x: Math.max(0, event.clientX - rect.left), y: Math.max(0, event.clientY - rect.top) }; }
  async function crop() { const element = canvas.current; if (!element || !start || !end || !pageUrl) return; const image = new Image(); image.src = pageUrl; await image.decode(); const left = Math.min(start.x, end.x); const top = Math.min(start.y, end.y); const width = Math.abs(start.x - end.x); const height = Math.abs(start.y - end.y); if (!width || !height) return; const scaleX = image.naturalWidth / element.clientWidth; const scaleY = image.naturalHeight / element.clientHeight; const output = document.createElement('canvas'); output.width = Math.round(width * scaleX); output.height = Math.round(height * scaleY); output.getContext('2d')?.drawImage(image, left * scaleX, top * scaleY, width * scaleX, height * scaleY, 0, 0, output.width, output.height); const blob = await toBlob(output); const sourceRegion: SourceRegion = { x: left / element.clientWidth, y: top / element.clientHeight, width: width / element.clientWidth, height: height / element.clientHeight }; const asset = await uploadCandidateAsset(candidateId, blob, sourceRegion); onChange([...assetIds, asset.id]); }
  return <section className="question-asset-editor"><strong>题目图片</strong><p>保留原图，无需裁剪。</p><div>{assetIds.map((id) => <figure key={id}>{assetUrls[id] ? <img src={assetUrls[id]} alt="题目已提取图片" /> : null}<button type="button" onClick={() => void remove(id)}>删除图片</button></figure>)}</div>{pageUrl ? <><canvas ref={canvas} aria-label="拖动选择裁剪区域" onMouseDown={(event) => setStart(point(event))} onMouseUp={(event) => setEnd(point(event))} /><button type="button" disabled={!start || !end} onClick={() => void crop()}>裁剪并上传</button></> : null}</section>;
}
